#!/usr/bin/zsh
#######################################
#
#    DarthSideous zsh expansion
#
#######################################

alias cthemes="~/themes/darth"
alias env-info="~/shell/env-info"

to_urxvt () {
	 sed -i.bak 's/^\*/URxvt./' $1
}
