#!/usr/bin/zsh
###########################
#
#     rsi zsh expansion
#
###########################


# Alias
alias vgascript="~/shell/vgascript"
alias gn="grep -n"

#Zstyles
zstyle ':completion:*' use-cache true
zstyle ':completion:*:history-words' stop yes
zstyle ':completion:*:history-words' remove-all-dups yes
zstyle ':completion:*:history-words' list false
zstyle ':completion:*:history-words' menu yes
zstyle ':completion:*' format '%B__%d___%b'
zstyle ':completion:*:warnings' format \
    "%B$fg[red]%}I cannot even make a good guess-- $fg[white]%d%b"
zstyle ':completion:*:messages' format '%B%U---- %d%u%b'

setopt nobeep
setopt hist_ignore_dups #don't save duplicate events
setopt hist_ignore_all_dups

# Compdef
compdef g=git
compdef _git gst=git-status
compdef _gdiff gdiff=git-diff
compdef _gpom gpom="git push origin master"

# Functions
to_urxvt () {
	 sed -i.bak 's/^\*/URxvt./' $1
}

git_prompt () {
autoload -Uz vcs_info

zstyle ':vcs_info:*' stagedstr '%F{28}●'
zstyle ':vcs_info:*' unstagedstr '%F{11}●'
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{11}%r'
zstyle ':vcs_info:*' enable git svn
precmd () {
    if [[ -z $(git ls-files --other --exclude-standard 2> /dev/null) ]] {
        zstyle ':vcs_info:*' formats ' [%F{green}%b%c%u%F{blue}]'
    } else {
        zstyle ':vcs_info:*' formats ' [%F{green}%b%c%u%F{red}●%F{blue}]'
    }

    vcs_info
}

setopt prompt_subst
RPROMPT='%F{blue}%n@%m %c${vcs_info_msg_0_}%F{blue} %(?/%F{blue}/%F{red})%% %{$reset_color%}'
}
# Custom Keybinds
# I've adjusted to liking these
bindkey "^B" backward-word
bindkey "^F" forward-word

# Antigen options
source ~/.antigen/antigen.zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle command-not-found

# Load all antigen setting before this line
antigen apply

# Custom Prompt
autoload -U colors && colors
RPROMPT="[%{$fg_no_bold[red]%}%?%{$reset_color%}]"
PROMPT="%{$fg[blue]%}╭─[%T%{$fg[red]%} %D%{$fg[blue]%}] %{$fg[green]%}%~ \
%{$fg[blue]%}
╰─%B$%b %{$reset_color%}"
